### ISSUE TITLE
Backload.Plugin.Database 2.2.8.0 usage on linux - error when loading plugin

### ISSUE THREAD

**Issue by kamillangowski** [blackcity/Backload#125]
Hi,

I am using debian v 8.7 and when trying to run 1 example (1.BasicDemo) from Backload.Database.Developer I am getting following error message:

System.Exception: Attaching of plugins failed ({0}).
   at Backload.Demo.Controllers.CustomDatabaseController.<DataHandler>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext() 

There seems to be some issue with plugin loading.

**Comment by kamillangowski** [comment]
Same example run on Windows works fine.

**Comment by blackcity** [comment]
Are you running it from Visual Studio Code? If so, please follow these steps:

1. Load the "6.More Demos" solution from the developer package. 
2. Open the "~/Controllers/CustomEventsController.cs" and  set breakpoints within the  `FileHandler` (including the catch block) and the events handler methods. 
3. Run the solution and choose the "Events demo" link.

I think it fails within the `hander.Init(...)` method. But some event hander should get invoked before like `Events_ConfigurationLoaded` or `Events_PreInitialization`.

Question:
What event handler get invoked an what exception do you receive?

**Comment by blackcity** [comment]
Try to set the plugin path manually. This must be done **before** the plugin will be loaded. You can use the `ConfigurationLoaded` event for this purpose (see `CustomEventsController.cs`):
void Events_ConfigurationLoaded(IFileHandler sender, Contracts.Eventing.IConfigurationLoadedEventArgs e)
{
    // Set correct plugin path for Linux
    string plugins = System.IO.Path.Combine(e.Context.BasePath.LocalServer, "Backload", "Plugin");
    e.Context.BasePath.PluginFolder = plugins;
}

**Comment by kamillangowski** [comment]
Thanks, adding ConfigurationLoaded event and setting plugins path manually solved the issue.

**Comment by blackcity** [comment]
Thanks for reporting. Will be fixed in the coming release.
